//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class appointment
    {
        [Required]
        [Display(Name ="Appointment ID")]
        public int id { get; set; }
        [Required]
        [Display(Name = "User ID")]
        public int userid { get; set; }
        [Required]
        [Display(Name = "Course ID")]
        public int courseid { get; set; }
    }
}
